#!/usr/bin/env python3
"""
Regression test: verify modular extractor produces identical v8 JSON output.

Compares the v8 JSON generated by the new modular sonification_extractor.py
against a reference JSON generated by the original monolith.

Usage:
    python src/tests/test_extractor_equivalence.py

Prerequisite:
    output/data/sonification_sc_v8_20110126_reference.json must exist
    (generated by the monolith before refactoring).
"""

import sys
import json
from pathlib import Path

import numpy as np

# Paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
OUTPUT_DATA = PROJECT_ROOT / "output" / "data"
REFERENCE = OUTPUT_DATA / "sonification_sc_v8_20110126_reference.json"
NEW_OUTPUT = OUTPUT_DATA / "sonification_sc_v8_20110126.json"


def compare_json(ref_path, new_path, atol=1e-10):
    """Compare two v8 JSON files field by field."""
    print("=" * 60)
    print("EXTRACTOR EQUIVALENCE TEST")
    print("=" * 60)

    if not ref_path.exists():
        print(f"FAIL: Reference file not found: {ref_path}")
        return False
    if not new_path.exists():
        print(f"FAIL: New output file not found: {new_path}")
        return False

    with open(ref_path) as f:
        ref = json.load(f)
    with open(new_path) as f:
        new = json.load(f)

    passed = 0
    failed = 0
    warnings = 0

    # --- Check top-level keys ---
    ref_keys = set(ref.keys())
    new_keys = set(new.keys())
    if ref_keys != new_keys:
        print(f"FAIL: Top-level keys differ: ref={ref_keys}, new={new_keys}")
        failed += 1
    else:
        print(f"OK: Top-level keys match: {sorted(ref_keys)}")
        passed += 1

    # --- Check '38kHz' data arrays ---
    ref_data = ref.get('38kHz', {})
    new_data = new.get('38kHz', {})

    ref_data_keys = set(ref_data.keys())
    new_data_keys = set(new_data.keys())

    missing = ref_data_keys - new_data_keys
    extra = new_data_keys - ref_data_keys
    if missing:
        print(f"FAIL: Missing fields in new output: {sorted(missing)}")
        failed += 1
    if extra:
        print(f"WARN: Extra fields in new output: {sorted(extra)}")
        warnings += 1
    if not missing and not extra:
        print(f"OK: 38kHz field set matches ({len(ref_data_keys)} fields)")
        passed += 1

    # --- Compare each array ---
    common_keys = sorted(ref_data_keys & new_data_keys)
    for key in common_keys:
        ref_arr = np.array(ref_data[key], dtype=float)
        new_arr = np.array(new_data[key], dtype=float)

        if ref_arr.shape != new_arr.shape:
            print(f"FAIL: {key} shape mismatch: ref={ref_arr.shape} new={new_arr.shape}")
            failed += 1
            continue

        if np.allclose(ref_arr, new_arr, atol=atol, equal_nan=True):
            passed += 1
        else:
            max_diff = float(np.nanmax(np.abs(ref_arr - new_arr)))
            n_diff = int(np.sum(~np.isclose(ref_arr, new_arr, atol=atol)))
            print(f"FAIL: {key} — max_diff={max_diff:.2e}, n_diff={n_diff}/{len(ref_arr)}")
            failed += 1

    # --- Check 'info' metadata ---
    ref_info = ref.get('info', {})
    new_info = new.get('info', {})

    info_keys_to_check = [
        'version', 'mode', 'num_points',
        'sunrise_h', 'sunset_h', 'dawn_end_h', 'dusk_start_h',
        'dvm_night_depth_m', 'dvm_day_depth_m',
        'dvm_shallow_anchor_m', 'dvm_deep_anchor_m',
    ]
    for key in info_keys_to_check:
        ref_val = ref_info.get(key)
        new_val = new_info.get(key)
        if ref_val is None and new_val is None:
            continue
        if isinstance(ref_val, (int, float)) and isinstance(new_val, (int, float)):
            if abs(ref_val - new_val) < 1e-6:
                passed += 1
            else:
                print(f"FAIL: info.{key} — ref={ref_val}, new={new_val}")
                failed += 1
        elif ref_val == new_val:
            passed += 1
        else:
            print(f"FAIL: info.{key} — ref={ref_val}, new={new_val}")
            failed += 1

    # --- Summary ---
    print()
    print("-" * 60)
    total = passed + failed
    if failed == 0:
        print(f"ALL PASSED: {passed}/{total} checks passed ({warnings} warnings)")
    else:
        print(f"FAILED: {failed}/{total} checks failed, {passed} passed ({warnings} warnings)")
    print("-" * 60)

    return failed == 0


if __name__ == "__main__":
    success = compare_json(REFERENCE, NEW_OUTPUT)
    sys.exit(0 if success else 1)
